### ISSUE TITLE
Running command with 'sudo' using pty

### ISSUE THREAD

**Issue by juriejan** [chuckmo/grunt-ssh#42]
Not sure what I'm missing here, but I can't seem to figure out how to make it possible for me to enter my password when attempting to run a command remotely with `sudo`.

Here's my configuration:

``` javascript
sshexec: {
  options: {
    host: '[host]',
    username: '[username]',
    agent: process.env.SSH_AUTH_SOCK,
    pty: true
  },
  ls: {
    command: 'sudo ls -la',
  }
}
```

So when I run the task just gets to the point where is asks for the password and stops. Doesn't react to anything I type in (which is what I exepected I guess):

```
Running "sshexec:ls" (sshexec) task
>> [sudo] password for [username]:
```

I'm using version 0.9 installed via NPM.

**Comment by vanBersie** [comment]
@gianpaj : your example worked like a charm! :) But I have another question about how to proceed. Let's say I want to fire some follow-up commands after the sudo login. How could I realize that? So in my example I use this command:

```
command: [
		  'echo \"<%= secret.password %>\" | sudo -S docker exec -i <docker_container> <docker_path> | ls'
		].join(' && '),
```
The command opens the docker container and when you do that in putty you can navigate through the docker files afterwards. But when I use the command above it seems that I'm still in the users directory. So is there a way to add a timeout or something to wait until the docker container is opened? I also tried to put the ls command in a seperate line but it was the same output. I know that with the && operator it waits until the first command was successful but still it's not the expected output. Any idea why? Thanks in advance!

**Comment by gianpaj** [comment]
@vanBersie 

i believe the issue is that there is only one element in the array of strings so the join function cannot "join" anything.
try an array of strings (separated by `'` quotes) and then the `join()` function.

see:
```js
> ['echo <> | docker | ls'].join(' && ')
"echo <> | docker | ls"
```

you want something like:
```js
> ['echo <>' , 'docker','ls'].join(' && ')
"echo <> && docker && ls"
```

See here for the difference between `&&`, `|` and `;`
https://unix.stackexchange.com/questions/159489/is-there-a-difference-between-and-and

**Comment by vanBersie** [comment]
@gianpaj : Thx! Yes the ls was misplaced there. Still it seems that I'm able to login but can't access the docker container from the grunt-ssh plugin. So with this:
```
command: [
		  'echo \"<%= secret.password %>\" | sudo -S docker exec -i ...',
		  'ls',
		  'sleep 5; ls'
		].join(' && '),
```
there is no error. But the two ls commands still show me the user folder and not the expected tomcat path in the docker container. If I add something after the password it displays the error "Sorry, try again.
 Incorrect password attempt". So I guess I have to find a different solution.
