### ISSUE TITLE
sftp does not support files in parent folder

### ISSUE THREAD

**Issue by leoliaolei** [chuckmo/grunt-ssh#62]
I have config like

````
sftp: {
   upload: {
    files: {
      "../staging/": "app-patch.zip"
    },
    options: {
                   ......
     }
  }
}
````

sftp throws error `>> Unable to copy; no valid source files were found.`. But file `../staging/app-patch.zip` does exist.

**Comment by viktorasm** [comment]
If anyone is curious for full solution, for me, to copy "../rcnode/target/rcnode.zip" file to "~/rcnode.zip", the setup was:

		sftp: {
			deploy: {
				files: {
					"./": "../rcnode/target/rcnode.zip"
				},
				options: {
					srcBasePath: "../rcnode/target/"
				}
			}
		},

**Comment by leoliaolei** [comment]
@viktorasm thanks, it works!
