### ISSUE TITLE
Fatal error: Malformed packet

### ISSUE THREAD

**Issue by cuweb** [chuckmo/grunt-ssh#93]
I'm getting this error when trying to deploy via sftp. Any ideas on what this could be?

**Comment by acramatte** [comment]
@cuweb I also have this since ssh2 was upgraded to 0.4.X.

There is a PR open to freeze ssh2 dependency to 0.3.x https://github.com/chuckmo/grunt-ssh/pull/92

In the meantime I had to use npm shrinkwrap.

**Comment by cuweb** [comment]
@acramatte Awesome, thanks! :+1:

**Comment by drinchev** [comment]
+1, I almost wrote a support ticket ot my CI :) Glad I found this issue.

**Comment by wwalmnes** [comment]
+1, finally found an explanation to this issue.

**Comment by andrewrjones** [comment]
Fixed in 0.12.1
