### ISSUE TITLE
Fire task after other task completes

### ISSUE THREAD

**Issue by Strutsagget** [chuckmo/grunt-ssh#99]
Hi I have a problem with the file uploaded to the server is always an old file. 

I have sass and then grunt-sass creates the css files i want to upload them to my server.

I can see the file changes and that a file is uploaded but i always end width an old version of the file.

If I manually save the css file again I can see again uploaded and the new version is uploaded to the server.

**Comment by chuckmo** [comment]
This needs to be accounted for in your Grunt setup, not this particular task. Make sure the ssh task is being run after sass completes.

Can you share a gist or something?

**Comment by Strutsagget** [comment]
thanx think i got it to work.
